name: prsclip
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.8 # for gsds cluster
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
    - opencv-python
    - einops
    - ftfy
    - timm
    - imageio
    - h5py
    